// Try Catch

const numero1 = 10;
const numero3 = 30;

console.log(numero1);

try {
    
} catch (error) {
    console.log(error);
}

console.log(numero3);